#golangci-lint configuration
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - unused

linters-settings:
  errcheck:
    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: false
    # Allow ignoring errors in defer statements
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - (*github.com/gofiber/fiber/v2.App).Listen
      - (*github.com/gofiber/fiber/v2.App).Test

issues:
  # Exclude certain linters from running on tests
  exclude-rules:
    # Exclude errcheck for test files for defer Close() calls
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value of .*(Close|Unmarshal|Test|Verify|Hash).*is not checked"

    #Allow unchecked errors in example files
    - path: example.*\.go
      linters:
        - errcheck

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0
